AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: OBC Bugyo Cloud proxy

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  BugyoCloudProxyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: bugyocloudproxy/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        BugyoCloudProxy:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /bcproxy
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  BugyoCloudProxyApi:
    Description: "API Gateway endpoint URL for Prod stage for Bugyo Cloud proxy"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/bcproxy/"
  BugyoCloudProxyFunction:
    Description: "Bugyo Cloud proxy Function ARN"
    Value: !GetAtt BugyoCloudProxyFunction.Arn
  BugyoCloudProxyFunctionIamRole:
    Description: "Implicit IAM Role created for Bugyo Cloud proxy"
    Value: !GetAtt BugyoCloudProxyFunctionRole.Arn
